development:
  adapter: postgresql
  encoding: unicode
  database: contacts_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: contacts_test
  pool: 5
  username: postgres
  password:
